application: kmj-lab2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# builtins:
# - appstats: on

derived_file_type:
- python_precompiled

libraries:
- name: jinja2
  version: "latest"

- name: webapp2
  version: "latest"

error_handlers:
- file: templates/errors/default_error.html

- error_code: over_quota
  file: templates/errors/over_quota.html

- error_code: dos_api_denial
  file: templates/errors/dos_api_denial.html

- error_code: timeout
  file: templates/errors/timeout.html

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.application
  login: admin

- url: /_ah/queue/deferred
  script: main.application
  login: admin
  
# - url: /_ah/stats.*
#   script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /admin/.*
  script: main.application
  login: admin

- url: /.*
  script: main.application